In [1]:
import numpy as np 
import matplotlib.pyplot as mtp  
import pandas as pd  
import csv

In [2]:
df = pd.read_csv('data1.csv')  
# file=open('data1.csv')
# csvreader=csv.reader(file)

In [3]:
df

     outlook temperature humidity  windy playgolf
0      rainy         hot     high  False       no
1      rainy         hot     high   True       no
2   overcast         hot     high  False      yes
3      sunny        mild     high  False      yes
4      sunny        cool   normal  False      yes
5      sunny        cool   normal   True       no
6   overcast        cool   normal   True      yes
7      rainy        mild     high  False       no
8      rainy        cool   normal  False      yes
9      sunny        mild   normal  False      yes
10     rainy        mild   normal   True      yes
11  overcast        mild     high   True      yes
12  overcast         hot   normal  False      yes
13     sunny        mild     high   True       no

In [52]:
df.columns

Index(['outlook', 'temperature', 'humidity', 'windy', 'playgolf'], dtype='object')

In [62]:
head=df.columns.values
dis={}
for i in head:
    dis[i]=df[i]
print(dis,end="")

{'outlook': 0        rainy
1        rainy
2     overcast
3        sunny
4        sunny
5        sunny
6     overcast
7        rainy
8        rainy
9        sunny
10       rainy
11    overcast
12    overcast
13       sunny
Name: outlook, dtype: object, 'temperature': 0      hot
1      hot
2      hot
3     mild
4     cool
5     cool
6     cool
7     mild
8     cool
9     mild
10    mild
11    mild
12     hot
13    mild
Name: temperature, dtype: object, 'humidity': 0       high
1       high
2       high
3       high
4     normal
5     normal
6     normal
7       high
8     normal
9     normal
10    normal
11      high
12    normal
13      high
Name: humidity, dtype: object, 'windy': 0     False
1      True
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10     True
11     True
12    False
13     True
Name: windy, dtype: bool, 'playgolf': 0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: playgolf, dtype: object}